# Copyright 2025 Vijaykumar Singh <singhvjd@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""False positive detection for codebase analysis results.

This module detects and filters false positive patterns in codebase analysis.
It identifies test-specific patterns, compatibility shims, generated code,
and other intentional patterns that may be flagged as issues but are not
actually problematic.

P1 Priority: High impact, low effort. Reduces noise in analysis results.

Design Patterns:
- Pattern Matching: Regex-based detection of known FP patterns
- Context Analysis: File path and content context for better accuracy
- Chain of Responsibility: Multiple detection methods in sequence

Usage:
    detector = FalsePositiveDetector()
    is_fp, reason = detector.is_likely_false_positive({
        "file_path": "tests/test_utils.rs",
        "issue_type": "global_mutable_state",
        "snippet": "static TEST_DATA: OnceLock<Vec<u8>> = OnceLock::new();",
    })
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

from victor.tools.verification.protocols import (
    ClaimIssue,
    FalsePositiveResult,
)

logger = logging.getLogger(__name__)


class FalsePositiveDetector:
    """Detects and filters false positive patterns in analysis results.

    Identifies patterns that are commonly flagged as issues but are
    intentional or acceptable in certain contexts.

    Attributes:
        custom_patterns: Additional patterns to add to defaults
        excluded_paths: Paths to skip FP detection for
    """

    # Default false positive patterns
    FALSE_POSITIVE_PATTERNS = {
        # Test-specific patterns
        "test_global_state": [
            r"#\[cfg\(test\)\]\s*static\s+\w+:\s*OnceLock",
            r"#\[test\]\s*static\s+\w+",
            r"test_(?:fixture|mock|data|helper).*static",
            r"TEST_.*:\s*OnceLock|Mutex|RwLock",
        ],
        "test_attribute": [
            r"#\[test\]\s*fn\s+\w+",
            r"#\[tokio::test\]",
            r"#\[rstest\]",
            r"#\[should_panic\]",
        ],
        "test_file_path": [
            r"(?i)^tests/",
            r"(?i)/tests/",
            r"(?i)/test_",
            r"(?i)_test\.rs$",
            r"(?i)_test\.py$",
            r"(?i)\.test\.",
            r"(?i)__tests__/",
            r"(?i)/spec/",
            r"(?i)/test\.rs$",  # Handle tests/test.rs pattern
        ],
        # Compatibility and migration patterns
        "compatibility_shim": [
            r"compatibility re-export",
            r"Root compatibility re-exports",
            r"temporary compatibility",
            r"migration shim",
            r"backward compatibility",
            r"legacy.*re-export",
        ],
        "documented_debt": [
            r"TD-[A-Z-]+:\s*\S+",
            r"TODO.*technical.*debt",
            r"FIXME.*debt",
            r"HACK.*refactor.*someday",
            r"TECHDEBT[:\s]",
        ],
        # Generated code patterns
        "generated_code": [
            r"# DO NOT EDIT\s*",
            r"Generated by",
            r"Code generated",
            r"@generated\s*$",
            r"This file is auto-generated",
            r"Auto-generated",
            r"DO NOT MODIFY",
        ],
        # Fixture and mock patterns
        "fixture_data": [
            r"fixtures?[/\\]",
            r"mock.*data",
            r"test.*fixtures?",
            r"stub_data",
            r"__mocks__[/\\]",
        ],
        # Allow-listed comments
        "intentional_pattern": [
            r"# intentional",
            r"// intentional",
            r"/* intentional",
            r"# by design",
            r"// by design",
            r"# intentional.*false.*positive",
            r"// ignore.*warning",
            r"# noqa",
            r"# pylint:disable",
        ],
    }

    # Patterns that indicate high false positive risk
    HIGH_RISK_PATTERNS = [
        r"(?i)/tests/",
        r"(?i)/fixtures/",
        r"(?i)/mocks/",
        r"(?i)_test\.",
        r"(?i)/__tests__/",
    ]

    def __init__(
        self,
        custom_patterns: Optional[Dict[str, List[str]]] = None,
        excluded_paths: Optional[Set[str]] = None,
    ):
        """Initialize false positive detector.

        Args:
            custom_patterns: Additional patterns to add to defaults
            excluded_paths: Paths where FP detection should be skipped
        """
        self._patterns = self._compile_patterns(self.FALSE_POSITIVE_PATTERNS)
        if custom_patterns:
            self._patterns.update(self._compile_patterns(custom_patterns))

        self._high_risk_patterns = [re.compile(p) for p in self.HIGH_RISK_PATTERNS]
        self._excluded_paths = excluded_paths or set()

    def _compile_patterns(
        self, patterns: Dict[str, List[str]]
    ) -> Dict[str, List[re.Pattern]]:
        """Compile regex patterns for efficiency.

        Args:
            patterns: Dictionary of pattern names to regex strings

        Returns:
            Dictionary with compiled patterns
        """
        compiled = {}
        for name, pattern_list in patterns.items():
            compiled[name] = [re.compile(p) for p in pattern_list]
        return compiled

    def is_likely_false_positive(
        self,
        issue: Dict[str, Any] | ClaimIssue,
    ) -> Tuple[bool, str, float]:
        """Check if an issue is likely a false positive.

        Args:
            issue: Issue dictionary or ClaimIssue object

        Returns:
            Tuple of (is_fp, reason, confidence)
        """
        # Normalize input
        if isinstance(issue, dict):
            issue_dict = issue
        else:
            issue_dict = issue.model_dump()

        file_path = issue_dict.get("file_path", "")
        snippet = issue_dict.get("snippet", "")
        issue_type = issue_dict.get("issue_type", "")

        # Skip FP detection for excluded paths
        if any(excluded in file_path for excluded in self._excluded_paths):
            return False, "Path excluded from FP detection", 0.0

        # Check each pattern category
        for category, patterns in self._patterns.items():
            for pattern in patterns:
                if self._matches_pattern(pattern, file_path, snippet, issue_type):
                    confidence = self._calculate_confidence(category, file_path)
                    reason = self._generate_reason(category, pattern.pattern, file_path)
                    return True, reason, confidence

        return False, "No false positive patterns matched", 0.0

    def _matches_pattern(
        self,
        pattern: re.Pattern,
        file_path: str,
        snippet: str,
        issue_type: str,
    ) -> bool:
        """Check if pattern matches any relevant field.

        Args:
            pattern: Compiled regex pattern
            file_path: File path to check
            snippet: Code snippet to check
            issue_type: Issue type to check

        Returns:
            True if pattern matches
        """
        # Check file path
        if file_path and pattern.search(file_path):
            return True

        # Check snippet
        if snippet and pattern.search(snippet):
            return True

        # Check issue type (for pattern categories that target specific types)
        if issue_type and pattern.search(issue_type):
            return True

        return False

    def _calculate_confidence(self, category: str, file_path: Optional[str]) -> float:
        """Calculate confidence in false positive determination.

        Args:
            category: Pattern category that matched
            file_path: File path for additional context

        Returns:
            Confidence score between 0.0 and 1.0
        """
        # Base confidence by category
        base_confidence = {
            "test_file_path": 0.95,
            "test_attribute": 0.90,
            "test_global_state": 0.85,
            "generated_code": 0.95,
            "fixture_data": 0.90,
            "compatibility_shim": 0.70,
            "documented_debt": 0.60,
            "intentional_pattern": 0.85,
        }.get(category, 0.5)

        # Increase confidence for high-risk paths
        if file_path:
            for pattern in self._high_risk_patterns:
                if pattern.search(file_path):
                    return min(base_confidence + 0.1, 1.0)

        return base_confidence

    def _generate_reason(self, category: str, pattern: str, file_path: str) -> str:
        """Generate human-readable reason for FP determination.

        Args:
            category: Pattern category
            pattern: Matched pattern string
            file_path: File path for context

        Returns:
            Human-readable explanation
        """
        reasons = {
            "test_file_path": f"File appears to be a test file: {file_path}",
            "test_attribute": "Code contains test-specific attributes",
            "test_global_state": "Global state is in test-specific code",
            "generated_code": "Code appears to be auto-generated",
            "fixture_data": "Code appears to be test fixture or mock data",
            "compatibility_shim": "Code appears to be an intentional compatibility shim",
            "documented_debt": "Issue is documented as technical debt",
            "intentional_pattern": "Code is marked as intentional",
        }

        base_reason = reasons.get(category, f"Matched pattern category: {category}")
        return f"{base_reason} (pattern: {pattern[:50]}...)"

    def check_test_context(self, issue: Dict[str, Any] | ClaimIssue) -> bool:
        """Check if issue is in test-specific context.

        Args:
            issue: Issue to check

        Returns:
            True if issue appears in test context
        """
        if isinstance(issue, dict):
            issue_dict = issue
        else:
            issue_dict = issue.model_dump()

        file_path = issue_dict.get("file_path", "")

        # Check file path patterns
        test_path_patterns = self._patterns.get("test_file_path", [])
        for pattern in test_path_patterns:
            if pattern.search(file_path):
                return True

        # Check snippet for test attributes
        snippet = issue_dict.get("snippet") or ""
        if snippet:  # Only check if snippet exists
            test_attr_patterns = self._patterns.get("test_attribute", [])
            for pattern in test_attr_patterns:
                if pattern.search(snippet):
                    return True

        return False

    def check_compatibility_shim(self, issue: Dict[str, Any] | ClaimIssue) -> bool:
        """Check if issue is an intentional compatibility shim.

        Args:
            issue: Issue to check

        Returns:
            True if issue appears to be a compatibility shim
        """
        if isinstance(issue, dict):
            issue_dict = issue
        else:
            issue_dict = issue.model_dump()

        snippet = issue_dict.get("snippet") or ""
        shim_patterns = self._patterns.get("compatibility_shim", [])

        for pattern in shim_patterns:
            if snippet and pattern.search(snippet):
                return True

        return False

    def check_documented_debt(self, issue: Dict[str, Any] | ClaimIssue) -> bool:
        """Check if issue is documented as technical debt.

        Args:
            issue: Issue to check

        Returns:
            True if issue is documented as debt
        """
        if isinstance(issue, dict):
            issue_dict = issue
        else:
            issue_dict = issue.model_dump()

        snippet = issue_dict.get("snippet") or ""
        description = issue_dict.get("description") or ""
        debt_patterns = self._patterns.get("documented_debt", [])

        for pattern in debt_patterns:
            if pattern.search(snippet) or pattern.search(description):
                return True

        return False

    def filter_issues(
        self,
        issues: List[Dict[str, Any] | ClaimIssue],
        min_fp_confidence: float = 0.7,
    ) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
        """Filter issues into genuine and false positive groups.

        Args:
            issues: List of issues to filter
            min_fp_confidence: Minimum confidence to classify as FP

        Returns:
            Tuple of (genuine_issues, false_positives)
        """
        genuine = []
        false_positives = []

        for issue in issues:
            is_fp, reason, confidence = self.is_likely_false_positive(issue)

            issue_dict = issue if isinstance(issue, dict) else issue.model_dump()
            issue_dict_with_reason = {**issue_dict, "fp_reason": reason}

            if is_fp and confidence >= min_fp_confidence:
                false_positives.append(issue_dict_with_reason)
            else:
                genuine.append(issue_dict_with_reason)

        return genuine, false_positives

    def get_false_positive_summary(
        self,
        issues: List[Dict[str, Any] | ClaimIssue],
    ) -> Dict[str, Any]:
        """Generate a summary of false positive analysis.

        Args:
            issues: List of issues to analyze

        Returns:
            Summary dictionary with statistics
        """
        total = len(issues)
        false_positives = 0
        category_counts: Dict[str, int] = {}

        for issue in issues:
            is_fp, _, confidence = self.is_likely_false_positive(issue)
            if is_fp:
                false_positives += 1

                # Track categories (simplified - would need to return category from is_likely_false_positive)
                if isinstance(issue, dict):
                    issue_dict = issue
                else:
                    issue_dict = issue.model_dump()

                file_path = issue_dict.get("file_path", "")
                if "test" in file_path.lower():
                    category_counts["test"] = category_counts.get("test", 0) + 1
                elif any(
                    pattern.search(file_path) for pattern in self._high_risk_patterns
                ):
                    category_counts["high_risk"] = category_counts.get("high_risk", 0) + 1

        return {
            "total_issues": total,
            "false_positives": false_positives,
            "genuine_issues": total - false_positives,
            "fp_rate": false_positives / total if total > 0 else 0.0,
            "category_breakdown": category_counts,
        }

    def add_custom_pattern(self, category: str, pattern: str) -> None:
        """Add a custom false positive pattern.

        Args:
            category: Pattern category name
            pattern: Regex pattern string
        """
        if category not in self._patterns:
            self._patterns[category] = []

        self._patterns[category].append(re.compile(pattern))

    def add_excluded_path(self, path: str) -> None:
        """Add a path to exclude from FP detection.

        Args:
            path: Path pattern to exclude
        """
        self._excluded_paths.add(path)
