---
extends: default

rules:
  line-length:
    max: 120
    level: warning

  indentation:
    spaces: 2
    indent-sequences: true

  comments:
    min-spaces-from-content: 1

  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0

  comments-indentation: {}

  document-start: disable

  empty-lines:
    max: 2

  trailing-spaces: {}

  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
