ollama pull qwen3-coder:30b
ollama pull deepseek-coder:33b
ollama pull deepseek-coder-v2:34b
ollama pull seed-36b
ollama pull gemma3:27b
ollama pull qwen2.5-coder:32b
ollama pull deepseek-coder-v2:16b
ollama pull qwen2.5-coder:14b
ollama pull seed-14b
ollama pull gemma3:12b
ollama pull mixtral:8x7b
ollama pull mixtral-8x7b
ollama pull mixtral-8x22b
ollama pull llama3.1:70b
ollama pull mistral:7b-instruct
ollama pull phi-4
ollama pull phi-4-mini
ollama pull llama3.1:8b
