# Data Cleaning Pipeline Workflow
# ================================
# Systematic data cleaning with validation loop:
# 1. Assess data quality issues
# 2. Plan cleaning strategy
# 3. Execute cleaning transformations
# 4. Validate results
# 5. Loop back if validation fails (up to max iterations)
# 6. Document changes

workflows:
  data_cleaning:
    description: "Systematic data cleaning with validation loop"

    metadata:
      version: "1.0"
      author: "victor"
      vertical: dataanalysis

    batch_config:
      batch_size: 1
      max_concurrent: 1
      retry_strategy: immediate
      max_retries: 2

    nodes:
      # =====================================================================
      # Stage 1: Quality Assessment
      # =====================================================================
      - id: init
        type: transform
        name: "Initialize State"
        transform: |
          iteration = 0
          max_iterations = 3
          validation_passed = false
        next: [assess_quality]

      - id: assess_quality
        type: agent
        name: "Assess Data Quality"
        role: analyst
        goal: |
          Thoroughly assess data quality issues:
          1. Count and locate missing values per column
          2. Identify duplicate rows
          3. Detect outliers using statistical methods
          4. Check data type consistency
          5. Validate value ranges and constraints
          6. Calculate overall quality score (0-1)

          Store findings in quality_report with structure:
          - missing_values: {column: count, ...}
          - duplicates: {count: N, indices: [...]}
          - outliers: {column: [indices], ...}
          - type_issues: [{column, expected, actual}, ...]
          - quality_score: 0.0-1.0
        tool_budget: 20
        tools: [read, shell]
        llm_config:
          temperature: 0.1
          model_hint: claude-3-sonnet
        input_mapping:
          data_path: data_path
        output: quality_report
        next: [check_quality]

      # =====================================================================
      # Stage 2: Quality Gate
      # =====================================================================
      - id: check_quality
        type: condition
        name: "Check Quality Threshold"
        condition: "quality_threshold"
        branches:
          "high_quality": document_changes
          "acceptable": plan_cleaning
          "needs_cleanup": plan_cleaning
          "default": plan_cleaning

      # =====================================================================
      # Stage 3: Plan Cleaning Strategy
      # =====================================================================
      - id: plan_cleaning
        type: agent
        name: "Plan Cleaning Strategy"
        role: planner
        goal: |
          Based on the quality report, create a detailed cleaning plan:

          **Missing Values Strategy:**
          - Columns with < 5% missing: Impute (mean/median/mode based on type)
          - Columns with 5-30% missing: Consider advanced imputation (KNN, MICE)
          - Columns with > 30% missing: Consider dropping or domain expertise

          **Duplicate Handling:**
          - Define which duplicates to keep (first, last, none)
          - Identify partial duplicates that need merge logic

          **Outlier Treatment:**
          - Statistical outliers (> 3 std): Winsorize or remove
          - Domain-based outliers: Flag for review

          **Type Corrections:**
          - List columns needing type conversion
          - Define parsing formats (dates, numbers)

          Output a structured cleaning_plan with ordered steps.
        tool_budget: 15
        tools: [read]
        llm_config:
          temperature: 0.2
        input_mapping:
          report: quality_report
          data_path: data_path
        output: cleaning_plan
        next: [execute_cleaning]

      # =====================================================================
      # Stage 4: Execute Cleaning
      # =====================================================================
      - id: execute_cleaning
        type: agent
        name: "Execute Cleaning"
        role: executor
        goal: |
          Execute the cleaning plan step by step:

          1. Create a backup of the original data
          2. Apply each cleaning step from the plan
          3. Log all transformations performed
          4. Save cleaned data to a new file

          Be careful to:
          - Not modify original data
          - Handle edge cases (all missing, empty columns)
          - Preserve column order and types
        tool_budget: 30
        tools: [shell, read, write]
        llm_config:
          temperature: 0.1
          model_hint: claude-3-sonnet
        input_mapping:
          plan: cleaning_plan
          data_path: data_path
        output: cleaned_data_path
        next: [validate_cleaning]

      # =====================================================================
      # Stage 5: Validation
      # =====================================================================
      - id: validate_cleaning
        type: agent
        name: "Validate Cleaned Data"
        role: reviewer
        goal: |
          Validate the cleaned data meets quality standards:

          1. Re-run quality assessment on cleaned data
          2. Compare before/after metrics
          3. Verify no data corruption occurred
          4. Check row count is within expected range
          5. Validate critical columns are intact

          Set validation_passed = true if:
          - Quality score improved
          - No critical data loss
          - All planned fixes were applied

          Update iteration count.
        tool_budget: 20
        tools: [read, shell]
        llm_config:
          temperature: 0.1
        input_mapping:
          original_report: quality_report
          cleaned_path: cleaned_data_path
        output: validation_result
        next: [update_iteration]

      - id: update_iteration
        type: transform
        name: "Update Iteration Count"
        transform: |
          iteration = iteration + 1
          validation_passed = validation_result.passed
        next: [retry_check]

      # =====================================================================
      # Stage 6: Retry Loop
      # =====================================================================
      - id: retry_check
        type: condition
        name: "Check Retry Condition"
        condition: "should_retry_cleaning"
        branches:
          "retry": assess_quality
          "done": human_review
          "default": human_review

      # =====================================================================
      # Stage 7: Human Review (Optional)
      # =====================================================================
      - id: human_review
        type: hitl
        name: "Review Cleaning Results"
        hitl_type: review
        prompt: |
          ## Data Cleaning Complete

          **Iterations:** {iteration}
          **Final Quality Score:** {validation_result.quality_score}

          **Summary of Changes:**
          {cleaning_summary}

          **Remaining Issues:**
          {remaining_issues}

          Please review and approve the cleaning results.
        context_keys:
          - iteration
          - validation_result
          - cleaning_summary
          - remaining_issues
        timeout: 900
        fallback: continue
        next: [document_changes]

      # =====================================================================
      # Stage 8: Documentation
      # =====================================================================
      - id: document_changes
        type: agent
        name: "Document Changes"
        role: writer
        goal: |
          Create comprehensive documentation of the cleaning process:

          1. **Data Lineage Report**
             - Original data location and characteristics
             - Cleaned data location
             - All transformations applied

          2. **Quality Improvement Summary**
             - Before/after quality metrics
             - Issues resolved

          3. **Recommendations**
             - Remaining data quality concerns
             - Suggested process improvements

          Save documentation as markdown file.
        tool_budget: 15
        tools: [write]
        llm_config:
          temperature: 0.4
        input_mapping:
          original_report: quality_report
          final_result: validation_result
          plan: cleaning_plan
        output: documentation_path
        next: [complete]

      - id: complete
        type: transform
        name: "Mark Complete"
        transform: |
          workflow_status = "completed"
          output_files = [cleaned_data_path, documentation_path]


  # =========================================================================
  # Quick Data Cleaning - Automated Fixes Only
  # =========================================================================
  data_cleaning_quick:
    description: "Quick automated data cleaning without human review"

    metadata:
      vertical: dataanalysis

    nodes:
      - id: quick_assess
        type: compute
        name: "Quick Quality Assessment"
        handler: stats_compute
        inputs:
          data: $ctx.data_path
          operations: [describe, missing_counts]
        output: quick_report
        constraints:
          llm_allowed: false
          timeout: 30
        next: [auto_clean]

      - id: auto_clean
        type: agent
        name: "Automated Cleaning"
        role: executor
        goal: |
          Apply standard cleaning operations:
          1. Drop rows with > 50% missing values
          2. Fill numeric missing with median
          3. Fill categorical missing with mode
          4. Remove exact duplicates
          Be fast and don't overthink.
        tool_budget: 15
        tools: [shell, write]
        llm_config:
          temperature: 0.0
          model_hint: claude-3-haiku
        output: cleaned_path
        next: [quick_summary]

      - id: quick_summary
        type: agent
        name: "Quick Summary"
        role: writer
        goal: "Write a 3-sentence summary of what was cleaned."
        tool_budget: 5
        llm_config:
          model_hint: claude-3-haiku
        output: summary
