# Homebrew Formula for Victor
# Copyright 2025 Vijaykumar Singh
#
# To install from a tap:
#   brew tap vijayksingh/tap
#   brew install victor
#
# To install from local formula:
#   brew install --build-from-source ./Formula/victor.rb
#
# Note: This formula is meant to be hosted in a separate tap repository:
#   https://github.com/vijayksingh/homebrew-tap

class Victor < Formula
  include Language::Python::Virtualenv

  desc "Enterprise-Ready AI Coding Assistant - Code to Victory with Any AI"
  homepage "https://github.com/vijayksingh/victor"
  url "https://github.com/vijayksingh/victor/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "REPLACE_WITH_ACTUAL_SHA256"
  license "Apache-2.0"
  head "https://github.com/vijayksingh/victor.git", branch: "main"

  # Bottles (pre-built binaries) - generated by CI
  # bottle do
  #   sha256 cellar: :any_skip_relocation, arm64_sonoma: "..."
  #   sha256 cellar: :any_skip_relocation, sonoma: "..."
  #   sha256 cellar: :any_skip_relocation, ventura: "..."
  #   sha256 cellar: :any_skip_relocation, x86_64_linux: "..."
  # end

  depends_on "python@3.12"
  depends_on "rust" => :build  # For some Python packages

  # Core dependencies
  resource "pydantic" do
    url "https://files.pythonhosted.org/packages/pydantic/pydantic-2.0.0.tar.gz"
    sha256 "REPLACE_WITH_SHA256"
  end

  # Add more resources as needed...
  # Run: pip-compile --generate-hashes requirements.txt
  # to generate the full list with hashes

  def install
    # Create virtual environment
    venv = virtualenv_create(libexec, "python3.12")

    # Install dependencies
    venv.pip_install resources

    # Install victor
    venv.pip_install_and_link buildpath

    # Generate shell completions
    generate_completions_from_executable(bin/"victor", shells: [:bash, :zsh, :fish], shell_parameter_format: :click)
  end

  def post_install
    # Create config directory
    (var/"victor").mkpath
  end

  def caveats
    <<~EOS
      Victor has been installed!

      Quick Start:
        1. Initialize in your project:
           victor init

        2. Start chatting:
           victor chat

        3. Or use the TUI:
           victor

      Configuration:
        Global config: ~/.victor/profiles.yaml
        Project config: .victor/init.md

      For more information:
        https://github.com/vijayksingh/victor
    EOS
  end

  test do
    # Test basic functionality
    assert_match "victor", shell_output("#{bin}/victor --version")

    # Test help output
    assert_match "Enterprise-Ready", shell_output("#{bin}/victor --help")

    # Test that config can be initialized
    system "#{bin}/victor", "init", "--quiet", testpath
    assert_predicate testpath/".victor", :directory?
  end
end
