# Copyright 2025 Vijaykumar Singh <singhvjd@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests for FalsePositiveDetector module."""

import pytest

from victor.tools.verification import (
    ClaimIssue,
    FalsePositiveDetector,
    IssueCategory,
)


class TestFalsePositiveDetector:
    """Tests for FalsePositiveDetector class."""

    @pytest.fixture
    def detector(self) -> FalsePositiveDetector:
        """Create a FalsePositiveDetector instance."""
        return FalsePositiveDetector()

    def test_detect_test_file(self, detector: FalsePositiveDetector):
        """Test detection of test files."""
        issue = ClaimIssue(
            issue_type="global_mutable_state",
            description="Global state in test",
            file_path="tests/test_utils.rs",
        )

        is_fp, reason, confidence = detector.is_likely_false_positive(issue)

        assert is_fp
        assert confidence > 0.7
        assert "test" in reason.lower()

    def test_detect_test_attribute(self, detector: FalsePositiveDetector):
        """Test detection of test attributes."""
        issue = ClaimIssue(
            issue_type="global_mutable_state",
            description="Global state with test attribute",
            snippet="#[test] fn test_something()",
        )

        is_fp, reason, confidence = detector.is_likely_false_positive(issue)

        assert is_fp
        assert "test" in reason.lower()

    def test_detect_compatibility_shim(self, detector: FalsePositiveDetector):
        """Test detection of compatibility shims."""
        issue = ClaimIssue(
            issue_type="re_export",
            description="Compatibility re-export",
            snippet="// Root compatibility re-exports",
        )

        is_fp, reason, confidence = detector.is_likely_false_positive(issue)

        assert is_fp
        assert "compatibility" in reason.lower()

    def test_detect_documented_debt(self, detector: FalsePositiveDetector):
        """Test detection of documented technical debt."""
        issue = ClaimIssue(
            issue_type="cross_layer_dependency",
            description="TD-CROSS-LAYER: Storage depends on Index",
            snippet="// TD-CROSS-LAYER: Known technical debt",
        )

        is_fp, reason, confidence = detector.is_likely_false_positive(issue)

        # Should be detected as FP (tracked debt)
        assert is_fp or "debt" in reason.lower()

    def test_detect_generated_code(self, detector: FalsePositiveDetector):
        """Test detection of generated code."""
        issue = ClaimIssue(
            issue_type="code_style",
            description="Generated file",
            snippet="// DO NOT EDIT - Auto-generated by build script",
        )

        is_fp, reason, confidence = detector.is_likely_false_positive(issue)

        assert is_fp
        assert confidence > 0.8
        assert "generated" in reason.lower()

    def test_no_false_positive(self, detector: FalsePositiveDetector):
        """Test case with no false positive patterns."""
        issue = ClaimIssue(
            issue_type="cross_layer_dependency",
            description="Storage module depends on Index module",
            file_path="src/storage/lib.rs",
            snippet="use crate::index::Index;",
        )

        is_fp, reason, confidence = detector.is_likely_false_positive(issue)

        assert not is_fp or confidence < 0.5  # Low or no FP risk

    def test_filter_issues(self, detector: FalsePositiveDetector):
        """Test filtering issues into genuine and false positives."""
        issues = [
            ClaimIssue(
                issue_type="test_issue",
                description="Test issue",
                file_path="tests/test.rs",
            ),
            ClaimIssue(
                issue_type="real_issue",
                description="Real issue",
                file_path="src/lib.rs",
            ),
        ]

        genuine, false_positives = detector.filter_issues(issues, min_fp_confidence=0.7)

        assert len(genuine) + len(false_positives) == 2
        assert len(false_positives) >= 1  # Test file should be FP

    def test_get_false_positive_summary(self, detector: FalsePositiveDetector):
        """Test generating FP summary."""
        issues = [
            ClaimIssue(issue_type="test", description="Test", file_path="tests/test.rs"),
            ClaimIssue(issue_type="real", description="Real", file_path="src/lib.rs"),
        ]

        summary = detector.get_false_positive_summary(issues)

        assert "total_issues" in summary
        assert "false_positives" in summary
        assert "fp_rate" in summary
        assert summary["total_issues"] == 2

    def test_check_test_context(self, detector: FalsePositiveDetector):
        """Test checking test context."""
        assert detector.check_test_context(ClaimIssue(issue_type="x", file_path="tests/test.rs"))
        assert not detector.check_test_context(ClaimIssue(issue_type="x", file_path="src/lib.rs"))

    def test_check_compatibility_shim(self, detector: FalsePositiveDetector):
        """Test checking for compatibility shims."""
        assert detector.check_compatibility_shim(
            ClaimIssue(issue_type="x", snippet="compatibility re-export")
        )
        assert not detector.check_compatibility_shim(
            ClaimIssue(issue_type="x", snippet="normal code")
        )

    def test_add_custom_pattern(self, detector: FalsePositiveDetector):
        """Test adding custom FP pattern."""
        detector.add_custom_pattern("custom", r"CUSTOM_PATTERN")

        issue = ClaimIssue(issue_type="x", snippet="some CUSTOM_PATTERN here")
        is_fp, _, _ = detector.is_likely_false_positive(issue)

        assert is_fp

    def test_add_excluded_path(self, detector: FalsePositiveDetector):
        """Test excluding paths from FP detection."""
        detector.add_excluded_path("critical/")

        issue = ClaimIssue(issue_type="test", file_path="critical/test.rs", snippet="#[test]")

        is_fp, _, _ = detector.is_likely_false_positive(issue)

        # Should be excluded from FP detection
        assert not is_fp or "excluded" in detector.is_likely_false_positive(issue)[1]
