from victor.core.attribution import (
    append_victor_commit_attribution,
    append_victor_pr_attribution,
    get_victor_attribution_identity,
)


def test_default_victor_commit_attribution() -> None:
    message = append_victor_commit_attribution("feat: add thing")

    assert message.startswith("feat: add thing")
    assert "Generated-by: victor-code-ai" in message
    assert (
        "Co-authored-by: victor-code-ai " "<296282796+victor-code-ai@users.noreply.github.com>"
    ) in message


def test_victor_commit_attribution_is_idempotent() -> None:
    message = append_victor_commit_attribution("fix: bug")
    assert append_victor_commit_attribution(message) == message


def test_victor_identity_can_be_overridden(monkeypatch) -> None:
    monkeypatch.setenv("VICTOR_AI_ATTRIBUTION_NAME", "victor-agent-ai")
    monkeypatch.setenv(
        "VICTOR_AI_ATTRIBUTION_EMAIL",
        "12345678+victor-agent-ai@users.noreply.github.com",
    )

    identity = get_victor_attribution_identity()

    assert identity.name == "victor-agent-ai"
    assert identity.email == "12345678+victor-agent-ai@users.noreply.github.com"
    assert (
        identity.coauthor_trailer
        == "Co-authored-by: victor-agent-ai <12345678+victor-agent-ai@users.noreply.github.com>"
    )


def test_victor_pr_attribution_is_idempotent() -> None:
    body = append_victor_pr_attribution("Summary")

    assert body.endswith("Generated by victor-code-ai.")
    assert append_victor_pr_attribution(body) == body
