# Copyright 2026 Vijaykumar Singh <singhvijay@users.noreply.github.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Shared Victor AI attribution helpers for Git commits and PR bodies."""

from __future__ import annotations

import os
from dataclasses import dataclass

DEFAULT_VICTOR_ATTRIBUTION_NAME = "victor-code-ai"
DEFAULT_VICTOR_ATTRIBUTION_EMAIL = "296282796+victor-code-ai@users.noreply.github.com"

ATTRIBUTION_NAME_ENV = "VICTOR_AI_ATTRIBUTION_NAME"
ATTRIBUTION_EMAIL_ENV = "VICTOR_AI_ATTRIBUTION_EMAIL"


@dataclass(frozen=True)
class AttributionIdentity:
    """Identity used in generated commit trailers and PR bodies."""

    name: str
    email: str

    @property
    def coauthor_trailer(self) -> str:
        return f"Co-authored-by: {self.name} <{self.email}>"

    @property
    def generated_by_trailer(self) -> str:
        return f"Generated-by: {self.name}"


def get_victor_attribution_identity() -> AttributionIdentity:
    """Return the configured Victor AI attribution identity.

    GitHub only links the co-author when ``email`` belongs to a verified
    GitHub account. Override ``VICTOR_AI_ATTRIBUTION_EMAIL`` with the claimed
    account's real noreply address after creating the account.
    """
    name = os.getenv(ATTRIBUTION_NAME_ENV, DEFAULT_VICTOR_ATTRIBUTION_NAME).strip()
    email = os.getenv(ATTRIBUTION_EMAIL_ENV, DEFAULT_VICTOR_ATTRIBUTION_EMAIL).strip()
    return AttributionIdentity(
        name=name or DEFAULT_VICTOR_ATTRIBUTION_NAME,
        email=email or DEFAULT_VICTOR_ATTRIBUTION_EMAIL,
    )


def append_victor_commit_attribution(message: str) -> str:
    """Append idempotent Git trailers for Victor AI attribution."""
    identity = get_victor_attribution_identity()
    message = (message or "").rstrip()
    existing_lines = set(message.splitlines())
    trailers = [
        identity.generated_by_trailer,
        identity.coauthor_trailer,
    ]
    missing = [trailer for trailer in trailers if trailer not in existing_lines]
    if not missing:
        return message
    return f"{message}\n\n" + "\n".join(missing)


def append_victor_pr_attribution(body: str) -> str:
    """Append idempotent branding attribution to a pull request body."""
    identity = get_victor_attribution_identity()
    body = (body or "").rstrip()
    marker = f"Generated by {identity.name}."
    if marker in body:
        return body
    return f"{body}\n\n---\n{marker}"
